spring.application.name=task-manager
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
spring.jackson.serialization.write-dates-as-timestamps=false
server.port=8080
